### ISSUE TITLE
ConsentForm doesn't hide selected elements.

### ISSUE THREAD

**Issue by juanfortuna** [academic-moodle-cooperation/moodle-mod_consentform#12]
Hi, I want to ask for some help. I'm using Moodle 4.2 and I just installed last plugin version. I'm setting up the Consent Form so if a student doesn't confirm he read a document, he can't do other activity. This activity is on another section and there's an image that links to a JS littel game on the same server. The thing is that a configure de plugin to not be able to play till you say yes to the rules, but it isn't working. I can click on image link without saying yes to consent form. Can you please help me? 
Tank you very much and sorry for my bad english, I am not a native speaker.

**Comment by bluetom** [comment]
Hi, with a consentform instance you control the availability of other course activities and/or ressources. This is not possible with the label ressource because this is always available. So if your image link is part of a label it is not controllable by the consentform instance. If you move the image link to a page ressource you can control it with a consentform instance....

**Comment by juanfortuna** [comment]
Thank you very much for the answer ... I will change it that way. By the way very usefull plugin! Great job, thank you!
